# Generated by Django 3.2.13 on 2024-09-23 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Salario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, null=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('nombre', models.CharField(max_length=200)),
                ('edad', models.IntegerField()),
                ('ciudad', models.CharField(max_length=70)),
                ('salario', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
            ],
            options={
                'verbose_name_plural': 'Salarios',
            },
        ),
    ]
