# Generated by Django 3.2.13 on 2024-09-23 22:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('salario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salario',
            name='usuario_creador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='salario_salario_creation', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salario',
            name='usuario_editor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='salario_salario_updated', to=settings.AUTH_USER_MODEL),
        ),
    ]
